name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Vision API Key File
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "facial-detection-key.json"
          json: ${{ secrets.FACIAL_DETECTION_KEY }}

      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
